/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooqcodegen;

import edu.java.scrapper.domain.jooqcodegen.tables.Chat;
import edu.java.scrapper.domain.jooqcodegen.tables.ChatLink;
import edu.java.scrapper.domain.jooqcodegen.tables.Databasechangelog;
import edu.java.scrapper.domain.jooqcodegen.tables.Databasechangeloglock;
import edu.java.scrapper.domain.jooqcodegen.tables.Link;
import edu.java.scrapper.domain.jooqcodegen.tables.LinkType;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chat</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.chat_link</code>.
     */
    public final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.link</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * The table <code>public.link_type</code>.
     */
    public final LinkType LINK_TYPE = LinkType.LINK_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }

    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            ChatLink.CHAT_LINK,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Link.LINK,
            LinkType.LINK_TYPE
        );
    }
}
