app:
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 1000s
  client:
    github-api-url: https://api.github.com  # для создание клиента с указанием base URL, пустое поле - используется base URL по умолчанию
    stackoverflow-api-url: https://api.stackexchange.com/2.3
    bot-api-url: http://localhost:8090
  database-access-type: jpa

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request limit\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: hours
