app:
  telegram-token: ${BOT_TOKEN}
  scrapper-client:
    base-url: http://localhost:8080
    retry:
      backoff-policy: exponential
      max-attempts: 3
      initial-backoff: 10s
      retryable-codes: 429, 500, 503
  kafka:
    consumer-properties:
      bootstrap-servers: localhost:9092
      group-id: link-updates
      auto-offset-reset: latest
      max-poll-interval-ms: 300_000
      enable-auto-commit: false
      concurrency: 1
    producer-properties:
      bootstrap-servers: localhost:9092
      acks-mode: all
      delivery-timeout: 60s
      linger-ms: 12_000
      batch-size: 1024
    updates-topic:
      name: updates
      partitions: 1
      replicas: 1
    updates-dlq-topic:
      name: updates_dlq
      partitions: 1
      replicas: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request limit\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: hours
