/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.Public;
import edu.java.scrapper.domain.jooq.tables.Chat.ChatPath;
import edu.java.scrapper.domain.jooq.tables.records.ChatLinkRecord;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLink extends TableImpl<ChatLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chat_link</code>
     */
    public static final ChatLink CHAT_LINK = new ChatLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatLinkRecord> getRecordType() {
        return ChatLinkRecord.class;
    }

    /**
     * The column <code>public.chat_link.chat_id</code>.
     */
    public final TableField<ChatLinkRecord, Long> CHAT_ID =
        createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chat_link.link_id</code>.
     */
    public final TableField<ChatLinkRecord, Long> LINK_ID =
        createField(DSL.name("link_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private ChatLink(Name alias, Table<ChatLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChatLink(Name alias, Table<ChatLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chat_link</code> table reference
     */
    public ChatLink(String alias) {
        this(DSL.name(alias), CHAT_LINK);
    }

    /**
     * Create an aliased <code>public.chat_link</code> table reference
     */
    public ChatLink(Name alias) {
        this(alias, CHAT_LINK);
    }

    /**
     * Create a <code>public.chat_link</code> table reference
     */
    public ChatLink() {
        this(DSL.name("chat_link"), null);
    }

    public <O extends Record> ChatLink(
        Table<O> path,
        ForeignKey<O, ChatLinkRecord> childPath,
        InverseForeignKey<O, ChatLinkRecord> parentPath
    ) {
        super(path, childPath, parentPath, CHAT_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatLinkPath extends ChatLink implements Path<ChatLinkRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> ChatLinkPath(
            Table<O> path,
            ForeignKey<O, ChatLinkRecord> childPath,
            InverseForeignKey<O, ChatLinkRecord> parentPath
        ) {
            super(path, childPath, parentPath);
        }

        private ChatLinkPath(Name alias, Table<ChatLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatLinkPath as(String alias) {
            return new ChatLinkPath(DSL.name(alias), this);
        }

        @Override
        public ChatLinkPath as(Name alias) {
            return new ChatLinkPath(alias, this);
        }

        @Override
        public ChatLinkPath as(Table<?> alias) {
            return new ChatLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<ChatLinkRecord> getPrimaryKey() {
        return Keys.CHAT_LINK_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY, Keys.CHAT_LINK__CHAT_LINK_LINK_ID_FKEY);
    }

    private transient ChatPath _chat;

    /**
     * Get the implicit join path to the <code>public.chat</code> table.
     */
    public ChatPath chat() {
        if (_chat == null) {
            _chat = new ChatPath(this, Keys.CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY, null);
        }

        return _chat;
    }

    private transient Link.LinkPath _link;

    /**
     * Get the implicit join path to the <code>public.link</code> table.
     */
    public Link.LinkPath link() {
        if (_link == null) {
            _link = new Link.LinkPath(this, Keys.CHAT_LINK__CHAT_LINK_LINK_ID_FKEY, null);
        }

        return _link;
    }

    @Override
    @NotNull
    public ChatLink as(String alias) {
        return new ChatLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatLink as(Name alias) {
        return new ChatLink(alias, this);
    }

    @Override
    @NotNull
    public ChatLink as(Table<?> alias) {
        return new ChatLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(String name) {
        return new ChatLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(Name name) {
        return new ChatLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLink rename(Table<?> name) {
        return new ChatLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink where(Condition condition) {
        return new ChatLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
