/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooqcodegen.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkType implements Serializable {

    private static final long serialVersionUID = 1L;

    private String type;

    public LinkType() {
    }

    public LinkType(LinkType value) {
        this.type = value.type;
    }

    @ConstructorProperties({"type"})
    public LinkType(
        @NotNull String type
    ) {
        this.type = type;
    }

    /**
     * Getter for <code>public.link_type.type</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 63)
    @NotNull
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.link_type.type</code>.
     */
    public void setType(@NotNull String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LinkType other = (LinkType) obj;
        if (this.type == null) {
            if (other.type != null) {
                return false;
            }
        } else if (!this.type.equals(other.type)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinkType (");

        sb.append(type);

        sb.append(")");
        return sb.toString();
    }
}
