/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq;

import edu.java.scrapper.domain.jooq.tables.Chat;
import edu.java.scrapper.domain.jooq.tables.ChatLink;
import edu.java.scrapper.domain.jooq.tables.Databasechangeloglock;
import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.LinkType;
import edu.java.scrapper.domain.jooq.tables.records.ChatLinkRecord;
import edu.java.scrapper.domain.jooq.tables.records.ChatRecord;
import edu.java.scrapper.domain.jooq.tables.records.DatabasechangeloglockRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkTypeRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CHAT_PKEY =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("chat_pkey"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatLinkRecord> CHAT_LINK_PKEY = Internal.createUniqueKey(ChatLink.CHAT_LINK,
        DSL.name("chat_link_pkey"),
        new TableField[] {ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID},
        true
    );
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(
        Databasechangeloglock.DATABASECHANGELOGLOCK,
        DSL.name("databasechangeloglock_pkey"),
        new TableField[] {Databasechangeloglock.DATABASECHANGELOGLOCK.ID},
        true
    );
    public static final UniqueKey<LinkRecord> LINK_PKEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> LINK_URL_KEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_url_key"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<LinkTypeRecord> LINK_TYPE_PKEY = Internal.createUniqueKey(LinkType.LINK_TYPE,
        DSL.name("link_type_pkey"),
        new TableField[] {LinkType.LINK_TYPE.TYPE},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, ChatRecord> CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY =
        Internal.createForeignKey(ChatLink.CHAT_LINK,
            DSL.name("chat_link_chat_id_fkey"),
            new TableField[] {ChatLink.CHAT_LINK.CHAT_ID},
            Keys.CHAT_PKEY,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<ChatLinkRecord, LinkRecord> CHAT_LINK__CHAT_LINK_LINK_ID_FKEY =
        Internal.createForeignKey(ChatLink.CHAT_LINK,
            DSL.name("chat_link_link_id_fkey"),
            new TableField[] {ChatLink.CHAT_LINK.LINK_ID},
            Keys.LINK_PKEY,
            new TableField[] {Link.LINK.ID},
            true
        );
    public static final ForeignKey<LinkRecord, LinkTypeRecord> LINK__FK_LINK_TYPE = Internal.createForeignKey(Link.LINK,
        DSL.name("fk_link_type"),
        new TableField[] {Link.LINK.TYPE},
        Keys.LINK_TYPE_PKEY,
        new TableField[] {LinkType.LINK_TYPE.TYPE},
        true
    );
}
